### ISSUE TITLE
Defi Product Management Telegram Group Link is broken

### ISSUE THREAD

**Issue by jrag0x** [Dijkstrax/awesome-defi-product-management#2]
This does not link to a Telegram group:
> DeFi Product Management is a telegram group dedicated to UX, memes, analytics, and growth of DeFi products

**Comment by 0xvadym** [comment]
Hey, thanks! I’m gonna change

**Comment by 0xvadym** [comment]
It works actually :)

**Comment by 0xvadym** [comment]
Fixed, thanks!
